package arrunchez.baumsoft.con.lafamiliaarrunchez.gendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "ALIMENTOS".
 */
public class Alimentos {

    private Long id;
    /** Not-null value. */
    private String alimento;

    public Alimentos() {
    }

    public Alimentos(Long id) {
        this.id = id;
    }

    public Alimentos(Long id, String alimento) {
        this.id = id;
        this.alimento = alimento;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAlimento() {
        return alimento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAlimento(String alimento) {
        this.alimento = alimento;
    }

}
