package arrunchez.baumsoft.con.lafamiliaarrunchez.gendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "AVATARS".
 */
public class Avatars {

    private Long id;
    /** Not-null value. */
    private String avatar;

    public Avatars() {
    }

    public Avatars(Long id) {
        this.id = id;
    }

    public Avatars(Long id, String avatar) {
        this.id = id;
        this.avatar = avatar;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getAvatar() {
        return avatar;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

}
