package arrunchez.baumsoft.con.lafamiliaarrunchez.gendao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;

import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Calimentos;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CALIMENTOS".
*/
public class CalimentosDao extends AbstractDao<Calimentos, Long> {

    public static final String TABLENAME = "CALIMENTOS";

    /**
     * Properties of entity Calimentos.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Estado = new Property(1, Boolean.class, "estado", false, "ESTADO");
        public final static Property Calificacion_id = new Property(2, long.class, "calificacion_id", false, "CALIFICACION_ID");
        public final static Property Alimento_id = new Property(3, long.class, "alimento_id", false, "ALIMENTO_ID");
    };

    private DaoSession daoSession;


    public CalimentosDao(DaoConfig config) {
        super(config);
    }
    
    public CalimentosDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CALIMENTOS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ESTADO\" INTEGER," + // 1: estado
                "\"CALIFICACION_ID\" INTEGER NOT NULL ," + // 2: calificacion_id
                "\"ALIMENTO_ID\" INTEGER NOT NULL );"); // 3: alimento_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CALIMENTOS\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Calimentos entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Boolean estado = entity.getEstado();
        if (estado != null) {
            stmt.bindLong(2, estado ? 1L: 0L);
        }
        stmt.bindLong(3, entity.getCalificacion_id());
        stmt.bindLong(4, entity.getAlimento_id());
    }

    @Override
    protected void attachEntity(Calimentos entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Calimentos readEntity(Cursor cursor, int offset) {
        Calimentos entity = new Calimentos( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0, // estado
            cursor.getLong(offset + 2), // calificacion_id
            cursor.getLong(offset + 3) // alimento_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Calimentos entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEstado(cursor.isNull(offset + 1) ? null : cursor.getShort(offset + 1) != 0);
        entity.setCalificacion_id(cursor.getLong(offset + 2));
        entity.setAlimento_id(cursor.getLong(offset + 3));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Calimentos entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Calimentos entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getCalificacionesDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getAlimentosDao().getAllColumns());
            builder.append(" FROM CALIMENTOS T");
            builder.append(" LEFT JOIN CALIFICACIONES T0 ON T.\"CALIFICACION_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN ALIMENTOS T1 ON T.\"ALIMENTO_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Calimentos loadCurrentDeep(Cursor cursor, boolean lock) {
        Calimentos entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Calificaciones calificaciones = loadCurrentOther(daoSession.getCalificacionesDao(), cursor, offset);
         if(calificaciones != null) {
            entity.setCalificaciones(calificaciones);
        }
        offset += daoSession.getCalificacionesDao().getAllColumns().length;

        Alimentos alimentos = loadCurrentOther(daoSession.getAlimentosDao(), cursor, offset);
         if(alimentos != null) {
            entity.setAlimentos(alimentos);
        }

        return entity;    
    }

    public Calimentos loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Calimentos> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Calimentos> list = new ArrayList<Calimentos>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Calimentos> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Calimentos> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
