package arrunchez.baumsoft.con.lafamiliaarrunchez.gendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Avatars;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Alimentos;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Participantes;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Calificaciones;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Calimentos;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Calidientes;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Last_score_foods;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Last_score_teeth;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Last_score_tale;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Mac_bluetooth;

import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.AvatarsDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.AlimentosDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.ParticipantesDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.CalificacionesDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.CalimentosDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.CalidientesDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Last_score_foodsDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Last_score_teethDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Last_score_taleDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Mac_bluetoothDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig avatarsDaoConfig;
    private final DaoConfig alimentosDaoConfig;
    private final DaoConfig participantesDaoConfig;
    private final DaoConfig calificacionesDaoConfig;
    private final DaoConfig calimentosDaoConfig;
    private final DaoConfig calidientesDaoConfig;
    private final DaoConfig last_score_foodsDaoConfig;
    private final DaoConfig last_score_teethDaoConfig;
    private final DaoConfig last_score_taleDaoConfig;
    private final DaoConfig mac_bluetoothDaoConfig;

    private final AvatarsDao avatarsDao;
    private final AlimentosDao alimentosDao;
    private final ParticipantesDao participantesDao;
    private final CalificacionesDao calificacionesDao;
    private final CalimentosDao calimentosDao;
    private final CalidientesDao calidientesDao;
    private final Last_score_foodsDao last_score_foodsDao;
    private final Last_score_teethDao last_score_teethDao;
    private final Last_score_taleDao last_score_taleDao;
    private final Mac_bluetoothDao mac_bluetoothDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        avatarsDaoConfig = daoConfigMap.get(AvatarsDao.class).clone();
        avatarsDaoConfig.initIdentityScope(type);

        alimentosDaoConfig = daoConfigMap.get(AlimentosDao.class).clone();
        alimentosDaoConfig.initIdentityScope(type);

        participantesDaoConfig = daoConfigMap.get(ParticipantesDao.class).clone();
        participantesDaoConfig.initIdentityScope(type);

        calificacionesDaoConfig = daoConfigMap.get(CalificacionesDao.class).clone();
        calificacionesDaoConfig.initIdentityScope(type);

        calimentosDaoConfig = daoConfigMap.get(CalimentosDao.class).clone();
        calimentosDaoConfig.initIdentityScope(type);

        calidientesDaoConfig = daoConfigMap.get(CalidientesDao.class).clone();
        calidientesDaoConfig.initIdentityScope(type);

        last_score_foodsDaoConfig = daoConfigMap.get(Last_score_foodsDao.class).clone();
        last_score_foodsDaoConfig.initIdentityScope(type);

        last_score_teethDaoConfig = daoConfigMap.get(Last_score_teethDao.class).clone();
        last_score_teethDaoConfig.initIdentityScope(type);

        last_score_taleDaoConfig = daoConfigMap.get(Last_score_taleDao.class).clone();
        last_score_taleDaoConfig.initIdentityScope(type);

        mac_bluetoothDaoConfig = daoConfigMap.get(Mac_bluetoothDao.class).clone();
        mac_bluetoothDaoConfig.initIdentityScope(type);

        avatarsDao = new AvatarsDao(avatarsDaoConfig, this);
        alimentosDao = new AlimentosDao(alimentosDaoConfig, this);
        participantesDao = new ParticipantesDao(participantesDaoConfig, this);
        calificacionesDao = new CalificacionesDao(calificacionesDaoConfig, this);
        calimentosDao = new CalimentosDao(calimentosDaoConfig, this);
        calidientesDao = new CalidientesDao(calidientesDaoConfig, this);
        last_score_foodsDao = new Last_score_foodsDao(last_score_foodsDaoConfig, this);
        last_score_teethDao = new Last_score_teethDao(last_score_teethDaoConfig, this);
        last_score_taleDao = new Last_score_taleDao(last_score_taleDaoConfig, this);
        mac_bluetoothDao = new Mac_bluetoothDao(mac_bluetoothDaoConfig, this);

        registerDao(Avatars.class, avatarsDao);
        registerDao(Alimentos.class, alimentosDao);
        registerDao(Participantes.class, participantesDao);
        registerDao(Calificaciones.class, calificacionesDao);
        registerDao(Calimentos.class, calimentosDao);
        registerDao(Calidientes.class, calidientesDao);
        registerDao(Last_score_foods.class, last_score_foodsDao);
        registerDao(Last_score_teeth.class, last_score_teethDao);
        registerDao(Last_score_tale.class, last_score_taleDao);
        registerDao(Mac_bluetooth.class, mac_bluetoothDao);
    }
    
    public void clear() {
        avatarsDaoConfig.getIdentityScope().clear();
        alimentosDaoConfig.getIdentityScope().clear();
        participantesDaoConfig.getIdentityScope().clear();
        calificacionesDaoConfig.getIdentityScope().clear();
        calimentosDaoConfig.getIdentityScope().clear();
        calidientesDaoConfig.getIdentityScope().clear();
        last_score_foodsDaoConfig.getIdentityScope().clear();
        last_score_teethDaoConfig.getIdentityScope().clear();
        last_score_taleDaoConfig.getIdentityScope().clear();
        mac_bluetoothDaoConfig.getIdentityScope().clear();
    }

    public AvatarsDao getAvatarsDao() {
        return avatarsDao;
    }

    public AlimentosDao getAlimentosDao() {
        return alimentosDao;
    }

    public ParticipantesDao getParticipantesDao() {
        return participantesDao;
    }

    public CalificacionesDao getCalificacionesDao() {
        return calificacionesDao;
    }

    public CalimentosDao getCalimentosDao() {
        return calimentosDao;
    }

    public CalidientesDao getCalidientesDao() {
        return calidientesDao;
    }

    public Last_score_foodsDao getLast_score_foodsDao() {
        return last_score_foodsDao;
    }

    public Last_score_teethDao getLast_score_teethDao() {
        return last_score_teethDao;
    }

    public Last_score_taleDao getLast_score_taleDao() {
        return last_score_taleDao;
    }

    public Mac_bluetoothDao getMac_bluetoothDao() {
        return mac_bluetoothDao;
    }

}
