package arrunchez.baumsoft.con.lafamiliaarrunchez.gendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Avatars;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Alimentos;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Participantes;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Calificaciones;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Calimentos;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.Calidientes;

import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.AvatarsDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.AlimentosDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.ParticipantesDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.CalificacionesDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.CalimentosDao;
import arrunchez.baumsoft.con.lafamiliaarrunchez.gendao.CalidientesDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig avatarsDaoConfig;
    private final DaoConfig alimentosDaoConfig;
    private final DaoConfig participantesDaoConfig;
    private final DaoConfig calificacionesDaoConfig;
    private final DaoConfig calimentosDaoConfig;
    private final DaoConfig calidientesDaoConfig;

    private final AvatarsDao avatarsDao;
    private final AlimentosDao alimentosDao;
    private final ParticipantesDao participantesDao;
    private final CalificacionesDao calificacionesDao;
    private final CalimentosDao calimentosDao;
    private final CalidientesDao calidientesDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        avatarsDaoConfig = daoConfigMap.get(AvatarsDao.class).clone();
        avatarsDaoConfig.initIdentityScope(type);

        alimentosDaoConfig = daoConfigMap.get(AlimentosDao.class).clone();
        alimentosDaoConfig.initIdentityScope(type);

        participantesDaoConfig = daoConfigMap.get(ParticipantesDao.class).clone();
        participantesDaoConfig.initIdentityScope(type);

        calificacionesDaoConfig = daoConfigMap.get(CalificacionesDao.class).clone();
        calificacionesDaoConfig.initIdentityScope(type);

        calimentosDaoConfig = daoConfigMap.get(CalimentosDao.class).clone();
        calimentosDaoConfig.initIdentityScope(type);

        calidientesDaoConfig = daoConfigMap.get(CalidientesDao.class).clone();
        calidientesDaoConfig.initIdentityScope(type);

        avatarsDao = new AvatarsDao(avatarsDaoConfig, this);
        alimentosDao = new AlimentosDao(alimentosDaoConfig, this);
        participantesDao = new ParticipantesDao(participantesDaoConfig, this);
        calificacionesDao = new CalificacionesDao(calificacionesDaoConfig, this);
        calimentosDao = new CalimentosDao(calimentosDaoConfig, this);
        calidientesDao = new CalidientesDao(calidientesDaoConfig, this);

        registerDao(Avatars.class, avatarsDao);
        registerDao(Alimentos.class, alimentosDao);
        registerDao(Participantes.class, participantesDao);
        registerDao(Calificaciones.class, calificacionesDao);
        registerDao(Calimentos.class, calimentosDao);
        registerDao(Calidientes.class, calidientesDao);
    }
    
    public void clear() {
        avatarsDaoConfig.getIdentityScope().clear();
        alimentosDaoConfig.getIdentityScope().clear();
        participantesDaoConfig.getIdentityScope().clear();
        calificacionesDaoConfig.getIdentityScope().clear();
        calimentosDaoConfig.getIdentityScope().clear();
        calidientesDaoConfig.getIdentityScope().clear();
    }

    public AvatarsDao getAvatarsDao() {
        return avatarsDao;
    }

    public AlimentosDao getAlimentosDao() {
        return alimentosDao;
    }

    public ParticipantesDao getParticipantesDao() {
        return participantesDao;
    }

    public CalificacionesDao getCalificacionesDao() {
        return calificacionesDao;
    }

    public CalimentosDao getCalimentosDao() {
        return calimentosDao;
    }

    public CalidientesDao getCalidientesDao() {
        return calidientesDao;
    }

}
