package arrunchez.baumsoft.con.lafamiliaarrunchez.gendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LAST_SCORE_TEETH".
 */
public class Last_score_teeth {

    private Long id;
    private String score;

    public Last_score_teeth() {
    }

    public Last_score_teeth(Long id) {
        this.id = id;
    }

    public Last_score_teeth(Long id, String score) {
        this.id = id;
        this.score = score;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getScore() {
        return score;
    }

    public void setScore(String score) {
        this.score = score;
    }

}
