package arrunchez.baumsoft.con.lafamiliaarrunchez.gendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MAC_BLUETOOTH".
 */
public class Mac_bluetooth {

    private Long id;
    private String mac;

    public Mac_bluetooth() {
    }

    public Mac_bluetooth(Long id) {
        this.id = id;
    }

    public Mac_bluetooth(Long id, String mac) {
        this.id = id;
        this.mac = mac;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMac() {
        return mac;
    }

    public void setMac(String mac) {
        this.mac = mac;
    }

}
